apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd.192.168.1.165.nip.io`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
