# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: python-app-dev
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/nkiriazis/python-app.git
#     targetRevision: HEAD
#     path: k8s/overlays/dev
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: dev
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nkiriazis/flask-app.git'
    targetRevision: HEAD
    path: devops-python-app  # You create this folder with your k8s manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
