apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nkiriazis/python-app.git
    targetRevision: HEAD
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
