apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flask-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`app.example.com`)
      kind: Rule
      services:
        - name: flask-app
          port: 8080
  tls:
    certResolver: letsencrypt
